### ISSUE TITLE
Uncaught exception exit code coherency

### ISSUE THREAD

**Issue by RazzM13** [martysweet/cfn-lint#121]
Apparently, when the `cfn-lint` cli executable encounters an uncaught exception during the `validate` command, it logs the exception's stack trace and returns a `0` exit code, implying that the program exited succesfully. However, at least from my limited point of view, this should not be the case due to the fact that it was actually unable to parse and determine the template's validity and therefore it should return a non-zero exit code, perhaps even a different one than for the invalid template scenario.

Steps to reproduce:
1) Create a `test.yaml` file that triggers an exception, perhaps with the following contents:
```
Resources:
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      Tags: null
```
2) Attempt to validate the file:
`cfn-lint validate test.yaml`
3) Observe the output and exit code:
[validate.log](https://github.com/martysweet/cfn-lint/files/1855988/validate.log)

Expected: A non-zero exit code.

**Comment by martysweet** [comment]
Thanks @RazzM13. Agreed, a non-zero code should be returned on a stack trace.

**Comment by RazzM13** [comment]
Hi @martysweet, I'll probably be looking at this tomorrow. In the mean time could you please shed some light upon the following question: given that exit code `1` is being used already, should we be using a different one and if so which?

**Comment by martysweet** [comment]
@RazzM13 

Just working from an example, according to http://www.tldp.org/LDP/abs/html/exitcodes.html, `1` would be "General Error" and `2` would be "Misuse of shell builtins".

I think the question we should ask is "would it be useful or confusing?". The important thing here is merging this change with issue #122, which will return a useful error message to be interpreted by a user.

Stack traces are thrown in a few funky edge cases, which can be caused by pure templating error, as opposed to cfn-lint bugs. While this is definitely something that can be improved, by isolating fault areas and bubbling errors, in the meantime, it may definitely cause confusion if we use different error codes. Especially when certain errors are try/catched in the future and the error code may change.

For this reason, I am swaying towards returning a `1` with an informative message. If you feel returning another value would be beneficial, let me know.

**Comment by RazzM13** [comment]
Please have a look at #125.
