### ISSUE TITLE
CloudFormation Stack Resoure - Passing Parameters causes uncaughtException

### ISSUE THREAD

**Issue by ssnorrizaurous** [martysweet/cfn-lint#55]
When using  an AWS::CloudFormation::Stack resource type, in both JSON and YAML, if parameters are passed under resource properties validation fails with _error: uncaughtException: Cannot read property 'hasOwnProperty_.  From error messages and my own troubleshooting, I believe that this bug is from validator.js's function checkResourceProperties, when it attempts process each property for property validation with _checkEachProperty(resourceType, resources[res], 'Properties');_. I've been able to replicate this the CloudFormation templates in
[replication.txt](https://github.com/martysweet/cfn-lint/files/1309173/replication.txt).

As a workaround, I've added a check for resource type prior to checkEachProperty that seems to resolve the error, but presumably removes the desired vetting of parameters for  AWS::CloudFormation::Stack. 
```               
if (resourceType !== 'AWS::CloudFormation::Stack') {
                    checkEachProperty(resourceType, resources[res], 'Properties');
}
```

**Comment by martysweet** [comment]
@ssnorrizaurous Could you try again with v1.3.4? The validator has been refactored. Thanks!

**Comment by RazzM13** [comment]
Hi @martysweet, I've just tried to validate the templates provided by @ssnorrizaurous using the latest version of the `master` branch and apparently they both pass, with a slight exception for the *json* format due to the property `TimeoutInMinutes` having a `Integer` *string* value instead of an actual *integer*, as defined by [the spec](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html#cfn-cloudformation-stack-timeoutinminutes).Perhaps this issue deserves closure?
